"""Add imageURI to Recipe model

Revision ID: c6f07241174b
Revises: d6f34a8bb0ab
Create Date: 2024-10-14 17:49:11.644196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6f07241174b'
down_revision = 'd6f34a8bb0ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imageURI', sa.String(), nullable=True))
        batch_op.drop_column('imageuri')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imageuri', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('imageURI')

    # ### end Alembic commands ###
